require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DistanceEssentialsController do

  # This should return the minimal set of attributes required to create a valid
  # DistanceEssential. As you add validations to DistanceEssential, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DistanceEssentialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all distance_essentials as @distance_essentials" do
      distance_essential = DistanceEssential.create! valid_attributes
      get :index, {}, valid_session
      assigns(:distance_essentials).should eq([distance_essential])
    end
  end

  describe "GET show" do
    it "assigns the requested distance_essential as @distance_essential" do
      distance_essential = DistanceEssential.create! valid_attributes
      get :show, {:id => distance_essential.to_param}, valid_session
      assigns(:distance_essential).should eq(distance_essential)
    end
  end

  describe "GET new" do
    it "assigns a new distance_essential as @distance_essential" do
      get :new, {}, valid_session
      assigns(:distance_essential).should be_a_new(DistanceEssential)
    end
  end

  describe "GET edit" do
    it "assigns the requested distance_essential as @distance_essential" do
      distance_essential = DistanceEssential.create! valid_attributes
      get :edit, {:id => distance_essential.to_param}, valid_session
      assigns(:distance_essential).should eq(distance_essential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DistanceEssential" do
        expect {
          post :create, {:distance_essential => valid_attributes}, valid_session
        }.to change(DistanceEssential, :count).by(1)
      end

      it "assigns a newly created distance_essential as @distance_essential" do
        post :create, {:distance_essential => valid_attributes}, valid_session
        assigns(:distance_essential).should be_a(DistanceEssential)
        assigns(:distance_essential).should be_persisted
      end

      it "redirects to the created distance_essential" do
        post :create, {:distance_essential => valid_attributes}, valid_session
        response.should redirect_to(DistanceEssential.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved distance_essential as @distance_essential" do
        # Trigger the behavior that occurs when invalid params are submitted
        DistanceEssential.any_instance.stub(:save).and_return(false)
        post :create, {:distance_essential => { "user" => "invalid value" }}, valid_session
        assigns(:distance_essential).should be_a_new(DistanceEssential)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DistanceEssential.any_instance.stub(:save).and_return(false)
        post :create, {:distance_essential => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested distance_essential" do
        distance_essential = DistanceEssential.create! valid_attributes
        # Assuming there are no other distance_essentials in the database, this
        # specifies that the DistanceEssential created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DistanceEssential.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => distance_essential.to_param, :distance_essential => { "user" => "" }}, valid_session
      end

      it "assigns the requested distance_essential as @distance_essential" do
        distance_essential = DistanceEssential.create! valid_attributes
        put :update, {:id => distance_essential.to_param, :distance_essential => valid_attributes}, valid_session
        assigns(:distance_essential).should eq(distance_essential)
      end

      it "redirects to the distance_essential" do
        distance_essential = DistanceEssential.create! valid_attributes
        put :update, {:id => distance_essential.to_param, :distance_essential => valid_attributes}, valid_session
        response.should redirect_to(distance_essential)
      end
    end

    describe "with invalid params" do
      it "assigns the distance_essential as @distance_essential" do
        distance_essential = DistanceEssential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DistanceEssential.any_instance.stub(:save).and_return(false)
        put :update, {:id => distance_essential.to_param, :distance_essential => { "user" => "invalid value" }}, valid_session
        assigns(:distance_essential).should eq(distance_essential)
      end

      it "re-renders the 'edit' template" do
        distance_essential = DistanceEssential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DistanceEssential.any_instance.stub(:save).and_return(false)
        put :update, {:id => distance_essential.to_param, :distance_essential => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested distance_essential" do
      distance_essential = DistanceEssential.create! valid_attributes
      expect {
        delete :destroy, {:id => distance_essential.to_param}, valid_session
      }.to change(DistanceEssential, :count).by(-1)
    end

    it "redirects to the distance_essentials list" do
      distance_essential = DistanceEssential.create! valid_attributes
      delete :destroy, {:id => distance_essential.to_param}, valid_session
      response.should redirect_to(distance_essentials_url)
    end
  end

end
